# Generated by Django 4.1.7 on 2023-04-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at', 'is_done']},
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(related_name='tasks', to='TaskProject.tag'),
        ),
    ]
